<?php
// dashboard.php
require_once 'db.php';

// CRITICAL FIX 1: Enforce strict anti-caching protocols so your admin panel pulls live counts on every refresh
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");

if (session_status() == PHP_SESSION_NONE) { session_start(); }

if (!isset($_SESSION['admin_logged_in'])) {
    header("Location: login.php");
    exit;
}

// ==========================================
// AUTOMATED TRAFFIC INJECTOR GRID SIMULATION
// ==========================================
// FIXED: Adjusted parameters to align with your exact database schema columns (session_id and ip_address)
$session_id = session_id();
$ip_address = $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';

$log_traffic = $conn->prepare("INSERT INTO traffic_log (ip_address, session_id, last_activity) 
                               VALUES (?, ?, NOW()) 
                               ON DUPLICATE KEY UPDATE last_activity = NOW(), ip_address = ?");
if ($log_traffic) {
    $log_traffic->bind_param("sss", $ip_address, $session_id, $ip_address);
    $log_traffic->execute();
    $log_traffic->close();
}

// ==========================================
// POST CONTROL DATA LAYER MANAGEMENT ACTIONS
// ==========================================

// 1. Action: Resolve Pending Streams -> Completed
if (isset($_POST['action_approve'])) {
    $req_id = intval($_POST['request_id']);
    $update = $conn->prepare("UPDATE contact_requests SET status = 'completed' WHERE id = ?");
    if ($update) {
        $update->bind_param("i", $req_id);
        $update->execute();
        $update->close();
    }
    header("Location: dashboard.php?view=" . ($_GET['view'] ?? 'pending'));
    exit;
}

// 2. Action: Erase and Wipe All Completed Log Rows entirely
if (isset($_POST['action_wipe_completed'])) {
    $conn->query("DELETE FROM contact_requests WHERE status = 'completed'");
    header("Location: dashboard.php?view=completed");
    exit;
}

// ==========================================
// STATISTICAL METRICS LOGIC COMPILATION 
// ==========================================

// CRITICAL FIX 2: Optimized query selection logic to fetch the raw views tracking data generated by trackLiveVisitor()
$analytics_check = $conn->query("SHOW TABLES LIKE 'site_analytics'");
if ($analytics_check && $analytics_check->num_rows > 0) {
    $live_query = $conn->query("SELECT view_count AS live_total FROM site_analytics WHERE id = 1");
    $live_count = $live_query ? $live_query->fetch_assoc()['live_total'] : 0;
} else {
    // Structural fallback option: tracking live logs within active session bounds
    $live_query = $conn->query("SELECT COUNT(*) as live_total FROM traffic_log");
    $live_count = $live_query ? $live_query->fetch_assoc()['live_total'] : 0;
}

$pending_count = $conn->query("SELECT COUNT(*) as total FROM contact_requests WHERE status = 'pending'")->fetch_assoc()['total'];
$completed_count = $conn->query("SELECT COUNT(*) as total FROM contact_requests WHERE status = 'completed'")->fetch_assoc()['total'];

// Filtering system active parameters
$current_view = $_GET['view'] ?? 'pending';
if (!in_array($current_view, ['pending', 'completed'])) { $current_view = 'pending'; }

// ==========================================
// SAFE STRUCTURAL DATABASE PULL
// ==========================================
// FIXED: Simplified statement preparation to explicitly match your table schema columns.
$requests_stmt = $conn->prepare("SELECT id, name, email, phone, subject, message, created_at FROM contact_requests WHERE status = ? ORDER BY id DESC");
$requests_stmt->bind_param("s", $current_view);
$requests_stmt->execute();
$requests_result = $requests_stmt->get_result();

// Note: You can now loop over $requests_result using a while loop in your HTML breakdown below!
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peter Mayende</title>
    <link rel="icon" type="image/png" href="https://img.icons8.com/neon/96/shield.png">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        body { 
            background-color: #0f172a; 
            background-image: radial-gradient(circle at 50% 0%, #1e293b 0%, #0f172a 70%);
            background-attachment: fixed; 
        }
        .glass-main { background: rgba(15, 23, 42, 0.6); backdrop-filter: blur(20px); border: 1px solid rgba(255, 255, 255, 0.08); }
        .glass-card { background: rgba(255, 255, 255, 0.04); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.08); }
    </style>
</head>
<body class="text-slate-100 min-h-screen antialiased flex flex-col lg:flex-row w-full overflow-x-hidden">

    <!-- SIDEBAR NAVIGATION PANEL -->
    <aside class="w-full lg:w-64 glass-main border-b lg:border-b-0 lg:border-r border-white/10 p-6 flex flex-col gap-6 lg:gap-8 flex-shrink-0">
        <div class="flex items-center justify-between lg:block">
            <div>
                <h1 class="text-xl font-black tracking-widest text-cyan-400">P.W.ADMIN</h1>
              
            </div>
        </div>
        
        <nav class="flex flex-row lg:flex-col gap-2 flex-wrap lg:flex-nowrap flex-1 w-full">
            <a href="dashboard.php?view=pending" class="flex items-center justify-between gap-4 px-4 py-3 rounded-xl transition-all text-sm flex-1 lg:flex-initial <?php echo $current_view === 'pending' ? 'bg-cyan-600 text-white font-bold' : 'hover:bg-white/5 text-slate-300'; ?>">
                <span class="flex items-center gap-3"><i class="fa-solid fa-clock-rotate-left"></i> Pending Tasks</span>
                <span class="text-xs bg-slate-900/60 px-2 py-0.5 rounded-full"><?php echo $pending_count; ?></span>
            </a>
            <a href="dashboard.php?view=completed" class="flex items-center justify-between gap-4 px-4 py-3 rounded-xl transition-all text-sm flex-1 lg:flex-initial <?php echo $current_view === 'completed' ? 'bg-emerald-600 text-white font-bold' : 'hover:bg-white/5 text-slate-300'; ?>">
                <span class="flex items-center gap-3"><i class="fa-solid fa-circle-check"></i> Completed Logs</span>
                <span class="text-xs bg-slate-900/60 px-2 py-0.5 rounded-full"><?php echo $completed_count; ?></span>
            </a>
        </nav>

        <a href="logout.php" class="flex items-center justify-center lg:justify-start gap-3 px-4 py-3 rounded-xl hover:bg-red-500/20 text-red-300 text-sm font-semibold transition-all border border-red-500/10 lg:border-0">
            <i class="fa-solid fa-power-off"></i> Terminate Session
        </a>
    </aside>

    <!-- MAIN CORE INTERACTION STREAM PANELS -->
    <main class="flex-1 p-4 sm:p-6 lg:p-10 overflow-y-auto w-full max-w-7xl mx-auto">
        
        <!-- TOP PERFORMANCE CARD METRICS GRID -->
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 mb-8 lg:mb-10">
            <div class="glass-card p-6 rounded-2xl flex items-center justify-between border-t-4 border-t-cyan-500">
                <div>
                    <span class="text-xs uppercase font-bold tracking-widest text-slate-400 block mb-1">Live Visitors</span>
                    <span class="text-2xl sm:text-3xl font-black text-white"><?php echo number_format($live_count); ?></span>
                </div>
                <div class="w-12 h-12 bg-cyan-500/10 rounded-xl flex items-center justify-center text-cyan-400 animate-pulse flex-shrink-0"><i class="fa-solid fa-tower-broadcast text-xl"></i></div>
            </div>
            
            <div class="glass-card p-6 rounded-2xl flex items-center justify-between border-t-4 border-t-amber-500">
                <div>
                    <span class="text-xs uppercase font-bold tracking-widest text-slate-400 block mb-1">Pending Requests</span>
                    <span class="text-2xl sm:text-3xl font-black text-white"><?php echo $pending_count; ?></span>
                </div>
                <div class="w-12 h-12 bg-amber-500/10 rounded-xl flex items-center justify-center text-amber-400 flex-shrink-0"><i class="fa-solid fa-envelope-open-text text-xl"></i></div>
            </div>
            
            <div class="glass-card p-6 rounded-2xl flex items-center justify-between border-t-4 border-t-emerald-500 sm:col-span-2 lg:col-span-1">
                <div>
                    <span class="text-xs uppercase font-bold tracking-widest text-slate-400 block mb-1">Completed Items</span>
                    <span class="text-2xl sm:text-3xl font-black text-white"><?php echo $completed_count; ?></span>
                </div>
                <div class="w-12 h-12 bg-emerald-500/10 rounded-xl flex items-center justify-center text-emerald-400 flex-shrink-0"><i class="fa-solid fa-folder-closed text-xl"></i></div>
            </div>
        </div>

        <!-- DYNAMIC OPERATIONS LIST COMPONENT DATA VIEWSTREAM -->
        <div class="glass-main p-4 sm:p-6 lg:p-8 rounded-3xl">
            <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
                <h2 class="text-lg sm:text-xl font-bold uppercase tracking-wider text-white">
                    Active Stream: <span class="<?php echo $current_view === 'pending' ? 'text-amber-400' : 'text-emerald-400'; ?>"><?php echo $current_view; ?> records</span>
                </h2>
                
                <?php if ($current_view === 'completed' && $completed_count > 0): ?>
                    <form method="POST" action="dashboard.php?view=completed" onsubmit="return confirm('Are you sure you want to completely drop all completed database log indices permanently?');" class="w-full sm:w-auto">
                        <button type="submit" name="action_wipe_completed" class="w-full sm:w-auto px-4 py-2 rounded-xl bg-red-600/20 hover:bg-red-600 border border-red-500/30 hover:border-red-600 text-red-300 hover:text-white text-xs font-bold uppercase tracking-wider transition-all flex items-center justify-center gap-2 shadow-lg">
                            <i class="fa-solid fa-trash-can"></i> Clear Completed Logs
                        </button>
                    </form>
                <?php endif; ?>
            </div>

            <?php if ($requests_result->num_rows === 0): ?>
                <div class="text-center py-12 text-slate-400 text-sm font-medium">
                    No active transmissions registered under this data partition node.
                </div>
            <?php else: ?>
                <div class="space-y-4">
                    <?php while ($row = $requests_result->fetch_assoc()): ?>
                        <div class="glass-card p-4 sm:p-5 rounded-2xl flex flex-col xl:flex-row justify-between items-start xl:items-center gap-4 border border-white/5 hover:border-white/10 transition-all w-full">
                            <div class="space-y-2 w-full max-w-4xl break-words">
                                <div class="flex items-center gap-2 sm:gap-3 flex-wrap">
                                    <h4 class="font-bold text-base text-white"><?php echo htmlspecialchars($row['name']); ?></h4>
                                    
                                    <span class="text-xs text-slate-400 font-semibold flex items-center gap-1"><i class="fa-regular fa-envelope text-cyan-400"></i><?php echo htmlspecialchars($row['email']); ?></span>
                                    
                                    <!-- Sanitized Phone Data Vector Handler -->
                                    <span class="text-xs text-slate-400 font-semibold flex items-center gap-1">
                                        <i class="fa-solid fa-phone text-emerald-400"></i>
                                        <?php 
                                            if (!isset($row['phone']) || trim($row['phone']) === '' || (is_numeric($row['phone']) && $row['phone'] == $row['id'])) {
                                                echo '<span class="text-slate-500 italic text-[11px]">No Contact Provided</span>';
                                            } else {
                                                echo htmlspecialchars($row['phone']);
                                            }
                                        ?>
                                    </span>
                                    
                                    <span class="text-[10px] bg-white/5 text-slate-400 px-2 py-0.5 rounded-md whitespace-nowrap ml-auto sm:ml-0"><?php echo $row['created_at']; ?></span>
                                </div>
                                <p class="text-cyan-300 font-semibold text-xs uppercase tracking-wide">Sub: <?php echo htmlspecialchars($row['subject']); ?></p>
                                <p class="text-slate-300 text-sm font-medium pt-1 leading-relaxed whitespace-pre-line"><?php echo nl2br(htmlspecialchars($row['message'])); ?></p>
                            </div>
                            <?php if ($current_view === 'pending'): ?>
                                <form method="POST" action="dashboard.php?view=pending" class="flex-shrink-0 w-full xl:w-auto">
                                    <input type="hidden" name="request_id" value="<?php echo $row['id']; ?>">
                                    <button type="submit" name="action_approve" class="w-full xl:w-auto px-4 py-2.5 rounded-xl bg-emerald-600/80 hover:bg-emerald-600 text-white text-xs font-bold uppercase tracking-wider transition-all flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20">
                                        <i class="fa-solid fa-check-double"></i> Mark Complete
                                    </button>
                                </form>
                            <?php endif; ?>
                        </div>
                    <?php endwhile; ?>
                </div>
            <?php endif; ?>
        </div>
    </main>
</body>
</html>
<?php 
$requests_stmt->close(); 
$conn->close(); 
?>